---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-server-pvc
  namespace: misctools
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-plugins-pvc
  namespace: misctools
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-configmap
  namespace: misctools
data:
  EULA: "TRUE"
  tty: "true"
  stdin_open: "true"
  restart: "unless-stopped"
  TYPE: "SPIGOT"
  FORCE_REDOWNLOAD: "true"
  TZ: "America/Sao_Paulo"
  RCON_PORT: "25575"
  MODE: "survival"
  ENABLE_COMMAND_BLOCK: "true"
  ONLINE_MODE: "false"
  LEVEL: "world"
  MOTD: "Minecraft Server on DigitalOcean Kubernetes"
  PVP: "true"
  RCON_PASSWORD: "minecraft"
  ENABLE_QUERY: "true"
  PLUGINS: |
    https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
    https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server-deployment
  namespace: misctools
spec:
  template:
    metadata:
      name: minecraft-server
      labels:
        app: minecraft-server
    spec:
      containers:
        - name: minecraft-server-container
          image: itzg/minecraft-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 25565
              name: java
            - containerPort: 25565
              name: query
              protocol: UDP
            - containerPort: 25575
              name: rcon
            - containerPort: 19132
              name: bedrock
              protocol: UDP
          volumeMounts:
            - name: minecraft-data
              mountPath: /data
            - name: minecraft-plugins
              mountPath: /plugins
          envFrom:
            - configMapRef:
                name: minecraft-configmap
      volumes:
        - name: minecraft-data
          persistentVolumeClaim:
            claimName: minecraft-server-pvc
        - name: minecraft-plugins
          persistentVolumeClaim:
            claimName: minecraft-plugins-pvc
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-svc
  namespace: misctools
spec:
  type: LoadBalancer
  selector:
    app: minecraft-server
  ports:
    # Java & Query
    - port: 25565
      targetPort: 25565
      name: java
      protocol: TCP
    # Query
    - port: 25565
      targetPort: 25565
      name: query
      protocol: UDP
    # Java RCON. Use a tool such as mcrcon to connect
    #- port: 25575
    #  targetPort: 25575
    #  name: rcon
    #  protocol: TCP
    # Bedrock
    - port: 19132
      targetPort: 19132
      protocol: UDP
      name: bedrock
