---
apiVersion: v1
kind: ConfigMap
metadata:
  name: transmission
  namespace: misctools
data:
  PGID: "1000"
  PUID: "1000"
  TZ: "America/Sao_Paulo"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: transmission
  namespace: misctools
spec:
  template:
    metadata:
      labels:
        app: transmission
    spec:
      containers:
        - name: transmission-container
          image: linuxserver/transmission
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9091
            - containerPort: 51413
          envFrom:
            - configMapRef:
                name: transmission
          volumeMounts:
            - name: downloads
              mountPath: /downloads
            - name: config
              mountPath: /config
            - name: watch
              mountPath: /watch
      volumes:
        - name: downloads
          hostPath:
            path: /mnt/hdexterno
            type: DirectoryOrCreate
        - name: watch
          hostPath:
            path: /opt/torrent/watch
            type: DirectoryOrCreate
        - name: config
          hostPath:
            path: /opt/torrent/config
            type: DirectoryOrCreate
  replicas: 1
  selector:
    matchLabels:
      app: transmission
---
apiVersion: v1
kind: Service
metadata:
  name: transmission
  namespace: misctools
spec:
  type: LoadBalancer
  selector:
    app: transmission
  ports:
    - name: gui
      protocol: TCP
      port: 9091
      nodePort: 30500
    - name: svc
      port: 51413
      nodePort: 30501
