---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: interlisp-data-pvc
  namespace: devtools
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: interlisp-deployment
  namespace: devtools
spec:
  template:
    metadata:
      name: interlisp
      labels:
        app: interlisp
    spec:
      containers:
        - name: interlisp-container
          image: interlisp/medley:221216-969bab0b_221207-098aa9b2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5900
              name: interlisp
          volumeMounts:
            - name: interlisp-data
              mountPath: /home/medley
      volumes:
        - name: interlisp-data
          persistentVolumeClaim:
            claimName: interlisp-data-pvc
  replicas: 1
  selector:
    matchLabels:
      app: interlisp
---
apiVersion: v1
kind: Service
metadata:
  name: interlisp-svc
  namespace: devtools
spec:
  type: LoadBalancer
  selector:
    app: interlisp
  ports:
    - port: 10001
      targetPort: 5900
      nodePort: 30200

