- name: Uninstall k3s on Workers
  become: true
  hosts: workers
  tasks:
    - name: Check connectivity with worker nodes
      ansible.builtin.ping:
    - name: Uninstall k3s agent
      command: /usr/local/bin/k3s-agent-uninstall.sh

- name: Uninstall k3s on Master
  become: true
  hosts: rpi4-master
  tasks:
    - name: Check connectivity with master node
      ansible.builtin.ping:
    - name: Uninstall k3s server
      command: /usr/local/bin/k3s-uninstall.sh
